# Generated by Django 5.2.1 on 2025-05-26 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_voucherfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherfile',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_files', to='sales.voucherduration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='sales.voucher'),
        ),
    ]
